name: Playwright Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd Week2
          npm ci

      - name: Install Playwright Browsers
        run: |
          cd Week2
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          cd Week2
          npx playwright test 